### ISSUE TITLE
Would it be possible to adapt this to support pause when say a video is playing?

### ISSUE THREAD

**Issue by Prn-Ice** [folixg/pause-on-lock#19]
For instance, I'd like to pause my music when I start watching a youtube video.

**Comment by folixg** [comment]
I don't know of a way to get the information whether there is a video playing in the browser. So sorry, can't help you here. But I'll leave the issue open maybe somebody who has an idea stumbles upon it.

**Comment by Prn-Ice** [comment]
Thanks, also it's not restricted to youtube, any video at all

**Comment by folixg** [comment]
I'm closing this now, because it is out of scope of this tool. However, I recently learned that firefox and chrome provide MPRIS interfaces, so you should be able to detect when a video starts playing in the browser. I think the library from [playerctl](https://github.com/altdesktop/playerctl#using-the-libraryl) might be a good starting point.
