### ISSUE TITLE
Does this really need to use playerctrl?

### ISSUE THREAD

**Issue by Brett-Holmes** [folixg/pause-on-lock#9]
Pause on lock used to be without dependencies and I found it to work fine, but now after updating it won't work with spotify for me without installing playerctrl 
which makes me install gtk-doc 
which makes me install libxslt 
which I need to have libxml2, 
and I end up at the end of the day having to install 13 dependencies for something that used to work just perfectly fine. I don't think going through playerctrl is the best option, and I only say this because I love using pause-on-lock, but I can't use it because I have problems installing the dependencies.

**Comment by folixg** [comment]
I added the playerctl dependency, because the code began to grew significantly as more and more people added their favorite player. In order to keep the code simple I thought it was easier to use playerctl instead of manually handling each player. I kept the Rhythmbox support, since it is Ubuntus default player. But as Spotify is probably the way that most people listen to music, I will add support for Spotify without playerctl again.
Thanks for your feedback.
